# Generated by Django 5.2.8 on 2025-12-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcharacteristic',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
